"""empty message

Revision ID: c36157189199
Revises: 
Create Date: 2022-11-21 18:36:11.181205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36157189199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('detail_address', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('running_time', sa.Integer(), nullable=True),
    sa.Column('age_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cinemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('detail_address', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('running_time', sa.Integer(), nullable=True),
    sa.Column('age_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('test_theaters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['test_cinemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theaters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showtimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_showtimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['test_cinemas.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['test_movies.id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['test_theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_theater_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('showtime_id', sa.Integer(), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['test_showtimes.id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['test_theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theater_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('showtime_id', sa.Integer(), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theater_tickets')
    op.drop_table('test_theater_tickets')
    op.drop_table('test_showtimes')
    op.drop_table('showtimes')
    op.drop_table('theaters')
    op.drop_table('test_theaters')
    op.drop_table('users')
    op.drop_table('tests')
    op.drop_table('test_users')
    op.drop_table('test_tests')
    op.drop_table('test_movies')
    op.drop_table('test_cinemas')
    op.drop_table('movies')
    op.drop_table('cinemas')
    # ### end Alembic commands ###
